import Mathlib
import ForkRaceFoldTheorems.TracedMonoidal
import ForkRaceFoldTheorems.CoarseningThermodynamics
import ForkRaceFoldTheorems.LandauerBeautyBridge

open scoped BigOperators ENNReal

namespace ForkRaceFoldTheorems

/-!
Thermodynamic Traced Monoidal Semantics

Connects TracedMonoidal.lean to the thermodynamic story. The key insight:
a trace application (feedback loop) is a coarsening step. Merging branches
through feedback = folding = erasure. Every non-trivial feedback loop generates
Landauer heat because the trace operator projects away the feedback component,
which is a many-to-one function when the feedback carries more than one value.

Main results:
1. Every non-trivial trace generates non-negative Landauer heat
2. Strictly positive heat when feedback carries >1 value
3. Iterated trace monotonically increases cumulative heat
4. Vanishing axiom (trivial trace) = zero heat
5. Systems with feedback get beauty optimality from fold-erasure
-/

/-! ### Traced coarsening steps -/

/-- A traced coarsening step: viewing the trace operator as a coarsening.
    The trace Tr(f) : A → B projects away the feedback component U,
    which corresponds to a quotient from A × U to A (via projection).
    When U has more than one element, this projection is many-to-one. -/
structure TracedCoarseningStep
    (A B U : Type) [Fintype A] [Fintype U] [Fintype (A × U)]
    [DecidableEq A] where
  /-- The morphism being traced -/
  f : GHom (A × U) (B × U)
  /-- Initial feedback value -/
  u₀ : U
  /-- Branch law on the product type (input × feedback) -/
  branchLaw : PMF (A × U)
  /-- Thermodynamic parameters -/
  boltzmannConstant : ℝ
  temperature : ℝ
  hBoltzmannPos : 0 < boltzmannConstant
  hTemperaturePos : 0 < temperature

/-- The projection that the trace performs: A × U → A.
    This is the "coarsening" step — projecting out the feedback component. -/
def traceProjection (A U : Type) : A × U → A := Prod.fst

/-- The heat generated by a trace application, viewed as the Landauer heat
    of projecting away the feedback component. -/
noncomputable def traceHeat
    (A U : Type) [Fintype A] [Fintype U] [Fintype (A × U)] [DecidableEq A]
    (boltzmannConstant temperature : ℝ)
    (branchLaw : PMF (A × U)) : ℝ :=
  coarseningLandauerHeat boltzmannConstant temperature
    branchLaw (traceProjection A U)

/-- Every trace generates non-negative Landauer heat when kT > 0.
    The projection A × U → A is a quotient, and quotient heat is non-negative. -/
theorem trace_heat_nonneg
    (A U : Type) [Fintype A] [Fintype U] [Fintype (A × U)] [DecidableEq A]
    (boltzmannConstant temperature : ℝ)
    (hkPos : 0 < boltzmannConstant) (hTPos : 0 < temperature)
    (branchLaw : PMF (A × U)) :
    0 ≤ traceHeat A U boltzmannConstant temperature branchLaw := by
  unfold traceHeat
  exact coarsening_landauer_heat_nonneg boltzmannConstant temperature
    hkPos hTPos branchLaw (traceProjection A U)

/-- Strictly positive heat when feedback carries more than one value:
    if there exist two elements (a, u₁) and (a, u₂) with u₁ ≠ u₂ in the
    support, then the projection is non-injective, generating positive heat. -/
theorem trace_heat_pos_of_nontrivial_feedback
    (A U : Type) [Fintype A] [Fintype U] [Fintype (A × U)] [DecidableEq A]
    (boltzmannConstant temperature : ℝ)
    (hkPos : 0 < boltzmannConstant) (hTPos : 0 < temperature)
    (branchLaw : PMF (A × U))
    (hNontrivial : ∃ a : A, ∃ u₁ u₂ : U, u₁ ≠ u₂ ∧
      0 < branchLaw (a, u₁) ∧ 0 < branchLaw (a, u₂)) :
    0 < traceHeat A U boltzmannConstant temperature branchLaw := by
  unfold traceHeat
  obtain ⟨a, u₁, u₂, hNe, hPos₁, hPos₂⟩ := hNontrivial
  apply coarsening_landauer_heat_pos_of_many_to_one boltzmannConstant temperature
    hkPos hTPos branchLaw (traceProjection A U)
  exact ⟨(a, u₁), (a, u₂), by
    intro h
    have : u₁ = u₂ := by
      have h1 := congr_arg Prod.snd h
      exact h1
    exact hNe this,
    rfl, hPos₁, hPos₂⟩

/-! ### Iterated trace heat monotonicity -/

/-- Iterated trace: tracing twice (first over U, then over V) generates
    at least as much heat as tracing once. The second trace is another
    coarsening step on top of the first.

    Formally: for the projection chain A × U × V → A × U → A,
    the cumulative heat of the full composition ≥ the heat of the first step. -/
theorem iterated_trace_heat_monotone
    (A U V : Type) [Fintype A] [Fintype U] [Fintype V]
    [Fintype (A × U)] [Fintype (A × U × V)] [Fintype ((A × U) × V)]
    [DecidableEq A] [DecidableEq (A × U)]
    (boltzmannConstant temperature : ℝ)
    (hkPos : 0 < boltzmannConstant) (hTPos : 0 < temperature)
    (branchLaw : PMF ((A × U) × V)) :
    coarseningLandauerHeat boltzmannConstant temperature
      branchLaw (traceProjection (A × U) V) ≤
    coarseningLandauerHeat boltzmannConstant temperature
      branchLaw ((traceProjection A U) ∘ (traceProjection (A × U) V)) := by
  exact cumulative_coarsening_heat_monotone boltzmannConstant temperature
    hkPos hTPos branchLaw (traceProjection (A × U) V) (traceProjection A U)

/-! ### Thermodynamic cost bundle -/

/-- Bundles a traced morphism with its thermodynamic heat cost.
    This is the "priced feedback" abstraction: every feedback loop
    comes with a mandatory Landauer heat bill. -/
structure FeedbackThermodynamicCost
    (A B U : Type) [Fintype A] [Fintype U] [Fintype (A × U)]
    [DecidableEq A] where
  /-- The morphism being traced -/
  f : GHom (A × U) (B × U)
  /-- Initial feedback value -/
  u₀ : U
  /-- Branch law on the input-feedback product -/
  branchLaw : PMF (A × U)
  /-- Thermodynamic parameters -/
  boltzmannConstant : ℝ
  temperature : ℝ
  hBoltzmannPos : 0 < boltzmannConstant
  hTemperaturePos : 0 < temperature
  /-- The heat cost of this feedback loop -/
  heatCost : ℝ := traceHeat A U boltzmannConstant temperature branchLaw
  /-- The heat cost is non-negative -/
  hHeatNonneg : 0 ≤ heatCost :=
    trace_heat_nonneg A U boltzmannConstant temperature
      hBoltzmannPos hTemperaturePos branchLaw

/-! ### Trace vanishing = zero heat -/

/-- The vanishing axiom from traced monoidal categories corresponds to zero heat:
    when the feedback type is PUnit (the monoidal unit), the trace is trivial
    and generates zero information loss.

    This is because the projection A × PUnit → A is an isomorphism (bijection),
    hence injective on support, hence zero conditional entropy, hence zero heat.

    Physically: feedback through a trivial channel carries no information,
    so no information is erased, so no heat is generated. -/
theorem trace_vanishing_heat
    (A : Type) [Fintype A] [Fintype (A × PUnit)] [DecidableEq A]
    (boltzmannConstant temperature : ℝ)
    (hkPos : 0 < boltzmannConstant) (hTPos : 0 < temperature)
    (branchLaw : PMF (A × PUnit)) :
    coarseningInformationLoss branchLaw (traceProjection A PUnit) = 0 := by
  unfold coarseningInformationLoss
  rw [(conditionalEntropyNats_eq_zero_iff_injective_on_support branchLaw
    (traceProjection A PUnit)).mpr]
  -- The projection A × PUnit → A is injective because PUnit has exactly one element
  intro ⟨a₁, u₁⟩ _ ⟨a₂, u₂⟩ _ hEq
  unfold traceProjection at hEq
  simp at hEq
  ext1
  · exact hEq
  · exact Subsingleton.elim u₁ u₂

/-- Vanishing heat corollary: zero Landauer heat when feedback type is PUnit. -/
theorem trace_vanishing_landauer_heat
    (A : Type) [Fintype A] [Fintype (A × PUnit)] [DecidableEq A]
    (boltzmannConstant temperature : ℝ)
    (hkPos : 0 < boltzmannConstant) (hTPos : 0 < temperature)
    (branchLaw : PMF (A × PUnit)) :
    traceHeat A PUnit boltzmannConstant temperature branchLaw = 0 := by
  unfold traceHeat coarseningLandauerHeat landauerHeatLowerBound
  rw [trace_vanishing_heat A boltzmannConstant temperature hkPos hTPos branchLaw]
  ring

/-! ### Feedback beauty floor -/

/-- Systems with non-trivial feedback get beauty optimality from the fold-erasure
    connection: the feedback loop is a fold (many-to-one projection), the fold
    erases information, erasure generates heat, and the heat establishes the
    observable coupling needed for beauty optimality.

    This constructs a CoarsenedSystem from the feedback structure. -/
noncomputable def feedbackToCoarsenedSystem
    (A U : Type) [Fintype A] [Fintype U] [Fintype (A × U)] [DecidableEq A]
    (branchLaw : PMF (A × U))
    (boltzmannConstant temperature : ℝ)
    (hBoltzmannPos : 0 < boltzmannConstant)
    (hTemperaturePos : 0 < temperature)
    (hNontrivial : ∃ a : A, ∃ u₁ u₂ : U, u₁ ≠ u₂ ∧
      0 < branchLaw (a, u₁) ∧ 0 < branchLaw (a, u₂)) :
    CoarsenedSystem (α := A × U) (β := A) where
  boltzmannConstant := boltzmannConstant
  temperature := temperature
  hBoltzmannPos := hBoltzmannPos
  hTemperaturePos := hTemperaturePos
  fineBranchLaw := branchLaw
  quotient := traceProjection A U
  hManyToOne := by
    obtain ⟨a, u₁, u₂, hNe, hPos₁, hPos₂⟩ := hNontrivial
    exact ⟨(a, u₁), (a, u₂), by
      intro h; exact hNe (congr_arg Prod.snd h),
      rfl, hPos₁, hPos₂⟩

/-- The feedback beauty floor: for systems with non-trivial feedback,
    the observable coupling from fold-erasure yields beauty optimality. -/
theorem feedback_beauty_floor
    (A U : Type) [Fintype A] [Fintype U] [Fintype (A × U)] [DecidableEq A]
    (branchLaw : PMF (A × U))
    (boltzmannConstant temperature : ℝ)
    (hBoltzmannPos : 0 < boltzmannConstant)
    (hTemperaturePos : 0 < temperature)
    (hNontrivial : ∃ a : A, ∃ u₁ u₂ : U, u₁ ≠ u₂ ∧
      0 < branchLaw (a, u₁) ∧ 0 < branchLaw (a, u₂)) :
    0 < coarseningLandauerHeat boltzmannConstant temperature
      branchLaw (traceProjection A U) := by
  exact coarsened_system_heat_positive
    (feedbackToCoarsenedSystem A U branchLaw boltzmannConstant temperature
      hBoltzmannPos hTemperaturePos hNontrivial)

end ForkRaceFoldTheorems
